name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - hieu
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
    - hieu

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: self-hosted
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v3
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        api_location: "/api"
        output_location: "public"
